name: api_tools
description: API tools
version: 1.1.0
homepage: https://github.com/abdulhaq-e/api_tools

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.4
  equatable: ^2.0.3
  path: ^1.8.0
  http_parser: ^4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^5.1.0
  test: ^1.22.0

flutter:
