name: api_tools
description: API tools
version: 0.0.1
homepage: https://github.com/abdulhaq-e/api_tools

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.2
  meta: ^1.1.8
  equatable: ^1.2.5
  path: ^1.7.0




dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: any

flutter: